workspace:
  base: /go
  path: src/github.com/getndazn/systemd-cloud-watch

pipeline:
  compile-binary:
    image: golang:1.10
    commands:
      - apt update && apt install libsystemd-dev -y
      - mkdir -p $GOPATH/src/github/${DRONE_REPO}
      - cp ./*.go $GOPATH/src/github/${DRONE_REPO}/
      - cp -r ./vendor/ $GOPATH/src/github/${DRONE_REPO}/
      - cd $GOPATH/src/github/${DRONE_REPO}
      - env GOOS=linux GOARCH=amd64 go build -o $DRONE_WORKSPACE/${DRONE_REPO_NAME}

  github-release:
      image: plugins/github-release
      secrets: [ github_token ]
      files: ./systemd-cloud-watch
      when:
        event: tag

