pipeline:
  build:
    image: golang:1.10
    commands:
      - mkdir -p $GOPATH/src/github/${DRONE_REPO}
      - cp ./*.go $GOPATH/src/github/${DRONE_REPO}/
      - cp -r ./vendor/ $GOPATH/src/github/${DRONE_REPO}/
      - cd $GOPATH/src/github/${DRONE_REPO}
      - env GOOS=linux GOARCH=amd64 go build -o $DRONE_WORKSPACE/${DRONE_REPO_NAME}
    when:
      event: push
      branch: master
